/*
 * LingConsole - A Server WebUI control panel
 * Copyright (C) 2026  XIAZHIRUI HUANG
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package im.xz.cn.lingconsole.app.panel.controller;

import im.xz.cn.lingconsole.app.panel.PanelConfig;
import im.xz.cn.lingconsole.app.panel.middleware.AuthMiddleware;
import im.xz.cn.lingconsole.common.model.ApiResponse;
import im.xz.cn.lingconsole.daemon.DaemonConfig;
import io.javalin.config.RoutesConfig;
import io.javalin.http.Context;

import java.util.LinkedHashMap;
import java.util.Map;


public class SettingsController {

    private static final String DAEMON_KEY_PLACEHOLDER = "<auto-generated-on-first-start>";

    private final PanelConfig panelConfig;
    private final DaemonConfig daemonConfig;
    public SettingsController(PanelConfig panelConfig, DaemonConfig daemonConfig) {
        this.panelConfig = panelConfig;
        this.daemonConfig = daemonConfig;
    }
    public void register(RoutesConfig routes, String prefix) {
        routes.get(prefix + "/settings", this::get);
    }

    private void get(Context ctx) {
        im.xz.cn.lingconsole.app.panel.model.AuthUser auth = AuthMiddleware.authUser(ctx);
        if (auth == null || !auth.isRoot()) {
            throw im.xz.cn.lingconsole.app.panel.exception.ApiException.forbidden("仅 root 可访问系统设置");
        }
        boolean privileged = auth.hasPermission(im.xz.cn.lingconsole.common.permission.Permissions.PERMISSION_ASSIGN);

        Map<String, Object> panel = new LinkedHashMap<>();
        panel.put("host", panelConfig.host());
        panel.put("port", panelConfig.port());
        panel.put("theme", panelConfig.theme());
        panel.put("language", panelConfig.language());
        if (privileged) {
            panel.put("sessionTimeout", panelConfig.sessionTimeout());
            panel.put("maxLoginAttempts", panelConfig.maxLoginAttempts());
            panel.put("lockoutDuration", panelConfig.lockoutDuration());
            panel.put("rateLimitPerSecond", panelConfig.rateLimitPerSecond());
            panel.put("loginBodyMaxBytes", panelConfig.loginBodyMaxBytes());
            panel.put("loginMaxConcurrent", panelConfig.loginMaxConcurrent());
            panel.put("passwordVerificationConcurrency", panelConfig.passwordVerificationConcurrency());
            panel.put("passwordVerificationTimeoutMillis", panelConfig.passwordVerificationTimeoutMillis());
            panel.put("socketAuthenticationTimeoutSeconds", panelConfig.socketAuthenticationTimeoutSeconds());
            panel.put("socketMaxTextMessageBytes", panelConfig.socketMaxTextMessageBytes());
            panel.put("socketMaxBinaryMessageBytes", panelConfig.socketMaxBinaryMessageBytes());
            panel.put("socketMaxAggregatedMessageBytes", panelConfig.socketMaxAggregatedMessageBytes());
            panel.put("socketMaxUnauthenticatedConnectionsPerIp", panelConfig.socketMaxUnauthenticatedConnectionsPerIp());
            panel.put("socketMaxConnections", panelConfig.socketMaxConnections());
            panel.put("socketMaxEventsPerSession", panelConfig.socketMaxEventsPerSession());
            panel.put("socketEventRateWindowSeconds", panelConfig.socketEventRateWindowSeconds());
        }

        Map<String, Object> daemon = new LinkedHashMap<>();
        if (privileged) {
            daemon.put("host", daemonConfig.host());
            daemon.put("port", daemonConfig.port());
            daemon.put("name", daemonConfig.name());
            daemon.put("whiteListEnabled", daemonConfig.whiteListEnabled());
            daemon.put("whiteListIps", daemonConfig.whiteListIps());
            daemon.put("authTimeout", daemonConfig.authTimeout());
            daemon.put("keyStatus", daemonKeyStatus(daemonConfig.key()));
            daemon.put("keyLength", daemonConfig.key() == null ? 0 : daemonConfig.key().length());
            daemon.put("maxFileTasks", daemonConfig.maxFileTasks());
            daemon.put("archiveCompressMaxEntries", daemonConfig.archiveCompress().maxEntries());
            daemon.put("archiveCompressMaxTotalBytes", daemonConfig.archiveCompress().maxTotalBytes());
            daemon.put("archiveCompressTimeoutSeconds", daemonConfig.archiveCompress().timeoutSeconds());
            daemon.put("archiveExtractMaxEntries", daemonConfig.archiveExtract().maxEntries());
            daemon.put("archiveExtractMaxTotalBytes", daemonConfig.archiveExtract().maxTotalBytes());
            daemon.put("archiveExtractTimeoutSeconds", daemonConfig.archiveExtract().timeoutSeconds());
            daemon.put("outputBufferSize", daemonConfig.outputBufferSize());
            daemon.put("outputBufferUnit", "lines");
            daemon.put("socketMaxTextMessageBytes", daemonConfig.socketMaxTextMessageBytes());
            daemon.put("socketMaxBinaryMessageBytes", daemonConfig.socketMaxBinaryMessageBytes());
            daemon.put("socketMaxAggregatedMessageBytes", daemonConfig.socketMaxAggregatedMessageBytes());
            daemon.put("socketMaxUnauthenticatedConnectionsPerIp", daemonConfig.socketMaxUnauthenticatedConnectionsPerIp());
            daemon.put("socketMaxConnections", daemonConfig.socketMaxConnections());
            daemon.put("socketMaxEventsPerSession", daemonConfig.socketMaxEventsPerSession());
            daemon.put("socketEventRateWindowSeconds", daemonConfig.socketEventRateWindowSeconds());
            daemon.put("softShutdownEnabled", daemonConfig.softShutdownEnabled());
            daemon.put("softShutdownWaitSeconds", daemonConfig.softShutdownWaitSeconds());
        }

        ctx.json(ApiResponse.ok(Map.of(
                "panel", panel,
                "daemon", daemon)));
    }

    private static String daemonKeyStatus(String key) {
        if (key == null || key.isBlank()) {
            return "EMPTY";
        }
        if (DAEMON_KEY_PLACEHOLDER.equals(key)) {
            return "PLACEHOLDER";
        }
        return key.length() > 8 ? "QUALIFIED" : "TOO_SHORT";
    }
}
