/*
 * LingConsole - A Server WebUI control panel
 * Copyright (C) 2026  XIAZHIRUI HUANG
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package im.xz.cn.lingconsole.daemon;

import im.xz.cn.lingconsole.common.config.Constants;
import im.xz.cn.lingconsole.common.config.TomlConfig;
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;


public class DaemonConfig extends TomlConfig {

    private static final long MIB = 1024L * 1024L;
    private static final long MAX_ARCHIVE_BYTES = 100L * 1024 * 1024 * 1024 * 1024;

    public static final String AUTO_KEY_PLACEHOLDER = "<auto-generated-on-first-start>";

    public enum KeyStatus {
        QUALIFIED, TOO_SHORT, EMPTY, PLACEHOLDER
    }

    private final String host;
    private final int port;
    private final String key;
    private final KeyStatus keyStatus;
    private final String name;
    private final boolean whiteListEnabled;
    private final List<String> whiteListIps;
    private final int authTimeout;
    private final boolean successUnlockOnceEnabled;
    private final String defaultAppPath;
    private final int maxFileTasks;
    private final ArchivePolicy archiveCompress;
    private final ArchivePolicy archiveExtract;
    private final int maxConcurrentDownloads;
    private final int downloadIdleTimeoutSeconds;
    private final int downloadMaxDurationSeconds;
    private final int outputBufferSize;
    private final int socketMaxTextMessageBytes;
    private final int socketMaxBinaryMessageBytes;
    private final int socketMaxAggregatedMessageBytes;
    private final int socketMaxUnauthenticatedConnectionsPerIp;
    private final int socketMaxConnections;
    private final int socketMaxEventsPerSession;
    private final int socketEventRateWindowSeconds;
    private final boolean softShutdownEnabled;
    private final int softShutdownWaitSeconds;
    private final String shellMode;

    private DaemonConfig(TomlParseResult r) {
        super(r);
        host = str("server.host", "0.0.0.0");
        port = intVal("server.port", Constants.DEFAULT_DAMON_PORT);
        key = str("auth.key", "");
        keyStatus = keyStatus(key);
        if (keyStatus != KeyStatus.QUALIFIED) {
            LoggerFactory.getLogger(DaemonConfig.class).warn(
                    "安全警告: Daemon Key 状态为 {}, 长度为 {}。空白 Key 无法认证，Key 至少 9 个字符才视为合格。",
                    keyStatus, key == null ? 0 : key.length());
        }
        name = str("auth.name", "local-daemon");
        whiteListEnabled = bool("auth.whiteListEnabled", false);
        whiteListIps = strList("auth.whiteListIps", List.of("127.0.0.1", "::1"));
        authTimeout = ranged("auth.authTimeout", 6, 1, 300);
        successUnlockOnceEnabled = bool("auth.successUnlockOnceEnabled", false);
        defaultAppPath = str("instance.defaultAppPath", Constants.APPS_DIR);
        maxFileTasks = ranged("instance.maxFileTasks", 2, 1, 64);
        archiveCompress = archivePolicy("archive.compress");
        archiveExtract = archivePolicy("archive.extract");
        maxConcurrentDownloads = ranged("download.maxConcurrent", 16, 1, 10_000);
        downloadIdleTimeoutSeconds = ranged("download.idleReadTimeoutSeconds", 30, 1, 86_400);
        downloadMaxDurationSeconds = ranged("download.maxDurationSeconds", 3600, 1, 86_400);
        outputBufferSize = ranged("instance.outputBufferSize", 256, 1, 100_000);
        socketMaxTextMessageBytes = ranged("socket.maxTextMessageBytes", 1024 * 1024, 1024, 64 * 1024 * 1024);
        socketMaxBinaryMessageBytes = ranged("socket.maxBinaryMessageBytes", 1024 * 1024, 1024, 64 * 1024 * 1024);
        socketMaxAggregatedMessageBytes = ranged("socket.maxAggregatedMessageBytes", 4 * 1024 * 1024, 1024, 64 * 1024 * 1024);
        if (socketMaxAggregatedMessageBytes < Math.max(socketMaxTextMessageBytes, socketMaxBinaryMessageBytes)) {
            throw new IllegalArgumentException("socket.maxAggregatedMessageBytes 不能小于文本或二进制消息限制");
        }
        socketMaxUnauthenticatedConnectionsPerIp = ranged(
                "socket.maxUnauthenticatedConnectionsPerIp", 20, 1, 10_000);
        socketMaxConnections = ranged("socket.maxConnections", 10_000, 1, 1_000_000);
        if (socketMaxUnauthenticatedConnectionsPerIp > socketMaxConnections) {
            throw new IllegalArgumentException("socket.maxUnauthenticatedConnectionsPerIp 不能大于 maxConnections");
        }
        socketMaxEventsPerSession = ranged("socket.maxEventsPerSession", 100, 1, 100_000);
        socketEventRateWindowSeconds = ranged("socket.eventRateWindowSeconds", 1, 1, 300);
        softShutdownEnabled = bool("instance.softShutdownEnabled", true);
        softShutdownWaitSeconds = ranged("instance.softShutdownWaitSeconds", 30, 1, 86_400);
        shellMode = str("terminal.shellMode", "auto");
    }

    public static DaemonConfig load(Path path) throws IOException {
        if (Files.exists(path)) {
            return new DaemonConfig(parse(path));
        }
        return new DaemonConfig(Toml.parse(""));
    }

    public String host() {
        return host;
    }

    public int port() {
        return port;
    }

    public String key() {
        return key;
    }

    public KeyStatus keyStatus() {
        return keyStatus;
    }

    public int keyLength() {
        return key == null ? 0 : key.length();
    }

    public static KeyStatus keyStatus(String key) {
        if (key == null || key.isBlank()) {
            return KeyStatus.EMPTY;
        }
        if (AUTO_KEY_PLACEHOLDER.equals(key)) {
            return KeyStatus.PLACEHOLDER;
        }
        return key.length() > 8 ? KeyStatus.QUALIFIED : KeyStatus.TOO_SHORT;
    }

    public String name() {
        return name;
    }

    public boolean whiteListEnabled() {
        return whiteListEnabled;
    }

    public List<String> whiteListIps() {
        return whiteListIps;
    }

    public int authTimeout() {
        return authTimeout;
    }

    public boolean successUnlockOnceEnabled() {
        return successUnlockOnceEnabled;
    }

    public String defaultAppPath() {
        return defaultAppPath;
    }

    public int maxFileTasks() {
        return maxFileTasks;
    }

    public ArchivePolicy archiveCompress() {
        return archiveCompress;
    }

    public ArchivePolicy archiveExtract() {
        return archiveExtract;
    }

    public int maxConcurrentDownloads() {
        return maxConcurrentDownloads;
    }

    public int downloadIdleTimeoutSeconds() {
        return downloadIdleTimeoutSeconds;
    }

    public int downloadMaxDurationSeconds() {
        return downloadMaxDurationSeconds;
    }

    public int outputBufferSize() {
        return outputBufferSize;
    }

    public int socketMaxTextMessageBytes() { return socketMaxTextMessageBytes; }
    public int socketMaxBinaryMessageBytes() { return socketMaxBinaryMessageBytes; }
    public int socketMaxAggregatedMessageBytes() { return socketMaxAggregatedMessageBytes; }
    public int socketMaxUnauthenticatedConnectionsPerIp() { return socketMaxUnauthenticatedConnectionsPerIp; }
    public int socketMaxConnections() { return socketMaxConnections; }
    public int socketMaxEventsPerSession() { return socketMaxEventsPerSession; }
    public int socketEventRateWindowSeconds() { return socketEventRateWindowSeconds; }

    public boolean softShutdownEnabled() {
        return softShutdownEnabled;
    }

    public int softShutdownWaitSeconds() {
        return softShutdownWaitSeconds;
    }

    
    public String shellMode() {
        return shellMode;
    }

    public static String defaultToml() {
        return """
                [server]
                host = "0.0.0.0"
                port = 55700

                [auth]
                key = "<auto-generated-on-first-start>"
                name = "local-daemon"
                whiteListEnabled = false
                whiteListIps = ["127.0.0.1", "::1"]
                authTimeout = 6
                successUnlockOnceEnabled = false

                [instance]
                defaultAppPath = "/lingConsole/apps"
                maxFileTasks = 2
                # application log lines retained per process
                outputBufferSize = 256
                softShutdownEnabled = true
                softShutdownWaitSeconds = 30

                [archive.compress]
                maxEntries = 100000
                maxTotalBytes = 209715200
                timeoutSeconds = 120

                [archive.extract]
                maxEntries = 100000
                maxTotalBytes = 209715200
                timeoutSeconds = 120

                [download]
                maxConcurrent = 16
                idleReadTimeoutSeconds = 30
                maxDurationSeconds = 3600

                [socket]
                maxTextMessageBytes = 1048576
                maxBinaryMessageBytes = 1048576
                maxAggregatedMessageBytes = 4194304
                maxUnauthenticatedConnectionsPerIp = 20
                maxConnections = 10000
                maxEventsPerSession = 100
                eventRateWindowSeconds = 1

                [terminal]
                shellMode = "auto"
                """;
    }

    private int ranged(String key, int def, int min, int max) {
        int value = intVal(key, def);
        if (value < min || value > max) {
            throw new IllegalArgumentException(key + " 必须在 " + min + " 到 " + max + " 之间");
        }
        return value;
    }

    private long rangedLong(String key, long def, long min, long max) {
        long value = longVal(key, def);
        if (value < min || value > max) {
            throw new IllegalArgumentException(key + " 必须在 " + min + " 到 " + max + " 之间");
        }
        return value;
    }

    private ArchivePolicy archivePolicy(String prefix) {
        long totalBytes = rangedLong(prefix + ".maxTotalBytes", 200L * MIB, MIB, MAX_ARCHIVE_BYTES);
        return new ArchivePolicy(
                rangedLong(prefix + ".maxEntries", 100_000, 1, 10_000_000),
                totalBytes,
                ranged(prefix + ".timeoutSeconds", 120, 1, 86_400));
    }

    public record ArchivePolicy(long maxEntries, long maxTotalBytes, int timeoutSeconds) {
    }
}
