/*
 * LingConsole - A Server WebUI control panel
 * Copyright (C) 2026  XIAZHIRUI HUANG
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package im.xz.cn.lingconsole.daemon;

import im.xz.cn.lingconsole.common.config.Constants;
import im.xz.cn.lingconsole.common.config.TomlConfig;
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;


public class DaemonConfig extends TomlConfig {

    private final String host;
    private final int port;
    private final String key;
    private final String name;
    private final boolean whiteListEnabled;
    private final List<String> whiteListIps;
    private final int authTimeout;
    private final String defaultAppPath;
    private final int maxFileTasks;
    private final int maxZipSize;
    private final int outputBufferSize;
    private final boolean softShutdownEnabled;
    private final int softShutdownWaitSeconds;
    private final String shellMode;

    private DaemonConfig(TomlParseResult r) {
        super(r);
        host = str("server.host", "0.0.0.0");
        port = intVal("server.port", Constants.DEFAULT_DAMON_PORT);
        key = str("auth.key", "");
        name = str("auth.name", "local-daemon");
        whiteListEnabled = bool("auth.whiteListEnabled", false);
        whiteListIps = strList("auth.whiteListIps", List.of("127.0.0.1", "::1"));
        authTimeout = intVal("auth.authTimeout", 6);
        defaultAppPath = str("instance.defaultAppPath", Constants.APPS_DIR);
        maxFileTasks = intVal("instance.maxFileTasks", 2);
        maxZipSize = intVal("instance.maxZipSize", 200);
        outputBufferSize = intVal("instance.outputBufferSize", 256);
        softShutdownEnabled = bool("instance.softShutdownEnabled", true);
        softShutdownWaitSeconds = intVal("instance.softShutdownWaitSeconds", 30);
        shellMode = str("terminal.shellMode", "auto");
    }

    public static DaemonConfig load(Path path) throws IOException {
        if (Files.exists(path)) {
            return new DaemonConfig(parse(path));
        }
        return new DaemonConfig(Toml.parse(""));
    }

    public String host() {
        return host;
    }

    public int port() {
        return port;
    }

    public String key() {
        return key;
    }

    public String name() {
        return name;
    }

    public boolean whiteListEnabled() {
        return whiteListEnabled;
    }

    public List<String> whiteListIps() {
        return whiteListIps;
    }

    public int authTimeout() {
        return authTimeout;
    }

    public String defaultAppPath() {
        return defaultAppPath;
    }

    public int maxFileTasks() {
        return maxFileTasks;
    }

    public int maxZipSize() {
        return maxZipSize;
    }

    public int outputBufferSize() {
        return outputBufferSize;
    }

    public boolean softShutdownEnabled() {
        return softShutdownEnabled;
    }

    public int softShutdownWaitSeconds() {
        return softShutdownWaitSeconds;
    }

    
    public String shellMode() {
        return shellMode;
    }

    public static String defaultToml() {
        return """
                [server]
                host = "0.0.0.0"
                port = 55700

                [auth]
                key = "<auto-generated-on-first-start>"
                name = "local-daemon"
                whiteListEnabled = false
                whiteListIps = ["127.0.0.1", "::1"]
                authTimeout = 6

                [instance]
                defaultAppPath = "/lingConsole/apps"
                maxFileTasks = 2
                maxZipSize = 200
                outputBufferSize = 256
                softShutdownEnabled = true
                softShutdownWaitSeconds = 30

                [terminal]
                shellMode = "auto"
                """;
    }
}
